services:
  - type: web
    name: alx-travel-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn alx_travel_app.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-travel-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: alx-travel-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: alx-travel-redis
          property: connectionString
      - key: EMAIL_HOST_USER
        value: "your-email@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "your-app-password"
      - key: CHAPA_SECRET_KEY
        value: "your_chapa_secret_key_here"

  - type: worker
    name: alx-travel-celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_travel_app worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-travel-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: alx-travel-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: alx-travel-redis
          property: connectionString
      - key: EMAIL_HOST_USER
        value: "your-email@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "your-app-password"

databases:
  - name: alx-travel-db
    databaseName: alx_travel_app
    user: alx_travel_user

services:
  - type: redis
    name: alx-travel-redis
    maxmemoryPolicy: allkeys-lru